RpcTools 5.x Add Ones Project: SamsungTVRemote Class Reference
SamsungTVRemote Class Reference
Public Member Functions
Create ()
RequestAction ($Ident, $Value)
Destroy ()
GetConfigurationForm ()
ResetGroups (bool $ResetMacros)
SendKey (string $Key)
SendMacro (string $Name)
Public Member Functions inherited from BaseRpcModule
Create ()
Register base propertys and profiles .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance of RpcTools .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Public Attributes
PROP_CURSOR =>'CURSOR',PROP_NUMBERS=>'NUMBERS',PROP_MEDIA=>'MEDIA',PROP_SOURCE=>'SOURCE',PROP_USER=>'USER']
Protected Member Functions
ApplyHost ($host, $doApply=true)
UpdateProps ($doApply=true)
GetPropDef ($Ident)
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
Validate current Configuration.
SetStatus ($Status)
Set Module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
SetDeviceState ($State)
CheckOnline ()
Checks if host online and setup devicestate.
GetProps ()
Get the device propertys.
SetProps (int $props, $Update=true, $doApply=true)
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Overide in your own Module.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
CreateVarByProp ($Prop)
CreateVarByIdent ($Ident, $CheckIdent=true)
ValidIdent ($Ident, $CheckProp=false)
CreateMissedProfile ($name)
GetPropDef ($Ident)
Returns variable definitions Must overide in your own Module.
GetModuleName ($name, $host)
IsLastInstance ($guid)
Protected Attributes
$prop_names = [PROP_MENU =>'MENU'
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Overide this to configure Timers for Module ONLINE_INTERVAL checks when device is Online OFFLINE_INTERVAL checks when device is offline Parameters for Checks are [0,'s'] first are the minimum value 0 = timer disabled second are the multiplicator s = seconds, m = minutes and h are hours.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable.
$online =null
if not checked Null, true if online false if host not reachable
$state =null
State cache 0=connected | 1=disconnected | 2=error.
$status = null
Status cache.
$prop_names = []
Contains a List of valid Propertys Key = Property value Value = Property ident name.
Private Member Functions
getDefaulteGroups ()
getDefaultKeyGroups ()
SendKeyCodeMacro ($macros)
SendKeyCodeEx ($k)
Private Attributes
$ValidKeys =['KEY_0','KEY_1','KEY_2','KEY_3','KEY_4','KEY_5','KEY_6','KEY_7','KEY_8','KEY_9','KEY_POWEROFF','KEY_MUTE','KEY_ENTER','KEY_EXIT','KEY_MENU','KEY_GUIDE','KEY_INFO','KEY_RETURN','KEY_SOURCE','KEY_TV','KEY_HDMI','KEY_HDMI2','KEY_RECORD','KEY_TOOLS','KEY_CHUP','KEY_CHDOWN','KEY_PLAY','KEY_PAUSE','KEY_STOP','KEY_NEXT','KEY_PREVIOUIS','KEY_FF','KEY_REWIND','KEY_VOLUP','KEY_VOLDOWN','KEY_UP','KEY_DOWN','KEY_LEFT','KEY_RIGHT']
Detailed Description
Definition at line 4 of file module.php.
Member Function Documentation
ApplyHost()
SamsungTVRemote::ApplyHost ($host, $doApply = true) protected
Definition at line 119 of file module.php.
Create()
SamsungTVRemote::Create ()
See also
IPSModule::Create()
Definition at line 9 of file module.php.
References getDefaulteGroups(), and getDefaultKeyGroups().
Destroy()
SamsungTVRemote::Destroy ()
See also
IPSModule::Destroy()
Definition at line 37 of file module.php.
GetConfigurationForm()
SamsungTVRemote::GetConfigurationForm ()
See also
IPSModule::GetConfigurationForm()
Definition at line 49 of file module.php.
getDefaulteGroups()
SamsungTVRemote::getDefaulteGroups () private
Definition at line 178 of file module.php.
References PROP_CURSOR, PROP_MEDIA, PROP_MENU, PROP_NUMBERS, PROP_SOURCE, and PROP_USER.
Referenced by Create(), and ResetGroups().
getDefaultKeyGroups()
SamsungTVRemote::getDefaultKeyGroups () private
Definition at line 188 of file module.php.
References PROP_CURSOR, PROP_MEDIA, PROP_MENU, PROP_NUMBERS, and PROP_SOURCE.
Referenced by Create(), and ResetGroups().
GetPropDef()
SamsungTVRemote::GetPropDef ($Ident) protected
Definition at line 161 of file module.php.
References PROP_CURSOR, PROP_MEDIA, PROP_MENU, PROP_NUMBERS, PROP_SOURCE, and PROP_USER.
RequestAction()
SamsungTVRemote::RequestAction ($Ident, $Value)
See also
IPSModule::RequestAction()
Definition at line 25 of file module.php.
References BaseRpcModule\CheckOnline(), SendKeyCodeEx(), and BaseRpcModule\SetValueByIdent().
ResetGroups()
SamsungTVRemote::ResetGroups (bool $ResetMacros)
Parameters
bool $ResetMacros
Definition at line 81 of file module.php.
References getDefaulteGroups(), and getDefaultKeyGroups().
SendKey()
SamsungTVRemote::SendKey (string $Key)
Parameters
string $Key
Returns
boolean
Definition at line 91 of file module.php.
References BaseRpcModule\CheckOnline(), and SendKeyCodeEx().
SendKeyCodeEx()
SamsungTVRemote::SendKeyCodeEx ($k) private
Definition at line 235 of file module.php.
Referenced by RequestAction(), SendKey(), and SendKeyCodeMacro().
SendKeyCodeMacro()
SamsungTVRemote::SendKeyCodeMacro ($macros) private
Definition at line 221 of file module.php.
References SendKeyCodeEx().
Referenced by SendMacro().
SendMacro()
SamsungTVRemote::SendMacro (string $Name)
Parameters
string $Name
Returns
boolean
Definition at line 102 of file module.php.
References BaseRpcModule\CheckOnline(), and SendKeyCodeMacro().
UpdateProps()
SamsungTVRemote::UpdateProps ($doApply = true) protected
Definition at line 129 of file module.php.
References BaseRpcModule\SetProps().
Member Data Documentation
$prop_names
array SamsungTVRemote::$prop_names = [PROP_MENU =>'MENU' protected
See also
IPSRpcModule::$prop_names
Definition at line 177 of file module.php.
$ValidKeys
SamsungTVRemote::$ValidKeys =['KEY_0','KEY_1','KEY_2','KEY_3','KEY_4','KEY_5','KEY_6','KEY_7','KEY_8','KEY_9','KEY_POWEROFF','KEY_MUTE','KEY_ENTER','KEY_EXIT','KEY_MENU','KEY_GUIDE','KEY_INFO','KEY_RETURN','KEY_SOURCE','KEY_TV','KEY_HDMI','KEY_HDMI2','KEY_RECORD','KEY_TOOLS','KEY_CHUP','KEY_CHDOWN','KEY_PLAY','KEY_PAUSE','KEY_STOP','KEY_NEXT','KEY_PREVIOUIS','KEY_FF','KEY_REWIND','KEY_VOLUP','KEY_VOLDOWN','KEY_UP','KEY_DOWN','KEY_LEFT','KEY_RIGHT'] private
Definition at line 211 of file module.php.
PROP_CURSOR
SamsungTVRemote::PROP_CURSOR =>'CURSOR',PROP_NUMBERS=>'NUMBERS',PROP_MEDIA=>'MEDIA',PROP_SOURCE=>'SOURCE',PROP_USER=>'USER']
Definition at line 177 of file module.php.
Referenced by getDefaulteGroups(), getDefaultKeyGroups(), and GetPropDef().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcAddOnes/SamsungTVRemote/module.php