RpcTools 5.x Add Ones Project: SonyAVRRemote Class Reference
SonyAVRRemote Class Reference
Public Member Functions
Create ()
RequestAction ($Ident, $Value)
Destroy ()
GetConfigurationForm ()
ResetGroups (bool $ResetMacros)
SendKey (string $Key)
SendMacro (string $Name)
Public Member Functions inherited from IPSRpcModule
Create ()
GetApi ()
GetApiInfo ()
Get current device api info.
Public Member Functions inherited from BaseRpcModule
Create ()
Register base propertys and profiles for Device .
ApplyChanges ()
Apply changes of instance configuration. If configuration not changed then calls BaseRpcModule::RunUpdate() .
Destroy ()
Cleanup unsused profiles if is last instance .
GetConfigurationForm ()
Load formular and handle Timers and Login fields .
RequestAction ($Ident, $Value)
Handle timer update events .
MessageSink ($TimeStamp, $SenderID, $Message, $Data)
Used to check Systemstartup and update each RpcTools device .
Public Attributes
PROP_CURSOR =>'CURSOR',PROP_NUMBERS=>'NUMBERS',PROP_MEDIA=>'MEDIA',PROP_SOURCE=>'SOURCE',PROP_SWITCH=>'SWITCH', PROP_USER=>'USER']
Protected Member Functions
GetModuleName ($name, $host)
GetDiscoverDeviceOptions ()
DoUpdate ()
UpdateProps ($doApply=true)
GetPropDef ($Ident)
Protected Member Functions inherited from IPSRpcModule
ApplyDeviceProps ($Props, $doApply)
DoUpdate ()
This function is called from RunUpdate and handle updates for status variables.
RunUpdate ()
GetDeviceConfig ()
Get config array to initilize RpcApi.
CreateApi ()
Return RpcApi object.
CallApi (string $function, array $arguments=[])
Make a rpc call.
GetDiscoverDeviceOptions ()
Get the default discover device config. Need to auto configure Device.
ApplyHost ($host, $doApply=true)
ReDiscover ()
RegisterHook ($Name, bool $Create)
Register a Hook for external calls.
ProcessHookData ()
Process the hook data.
Protected Member Functions inherited from BaseRpcModule
ValidateConfiguration ()
Validate current configuration.
SetStatus ($Status)
Set module status .
GetStatus ()
Return current instance status.
GetDeviceState ()
Get device state.
SetDeviceState ($State)
Set device state.
CheckOnline ()
Checks if host online and setup devicestate.
GetProps ()
Get the module propertys.
SetProps (int $props, $Update=true, $doApply=true)
Setup module propertys.
UpdateDeviceProps ($props, $AutoCreate=true, $AutoRemove=true)
Update module status variables by propertys.
UpdateProps ($doApply=true)
Update device property is called from ApplyChanges Override in your own Module.
ValidateTimers ()
Checks if TimerValues are Ok This function is called from ApplyChanges and check timer values based on BaseRpcModule::$timerDef.
StopTimer ()
Stop current Timer.
StartTimer ($delay=0)
Start timer based on BaseRpcModule::$timerDef.
RunUpdate ()
Main Update Caller , this will be call from TIMER, APPLY and SystemStartup.
ApplyHost ($host, $doApply=true)
Checks and Setup given host.
GetValueByIdent ($Ident)
Get status variable value by ident.
SetValueByIdent ($Ident, $Value, $force=true, $AutoCreate=true)
Set status variable value by ident.
CreateVarByProp ($Prop)
Create status variable by module property.
CreateVarByIdent ($Ident, $CheckIdent=true)
Create status variable by ident.
ValidIdent ($Ident, $CheckProp=false)
Checks if ident valid.
CreateMissedProfile ($name)
Is called if a profile missed.
GetPropDef ($Ident)
Returns status variable definition.
GetModuleName ($name, $host)
Is called once if module created or Configuration valid.
IsLastInstance ($guid)
Checks if more instances created with then given module ID.
Protected Attributes
$showLogin =[false,false]
$prop_names = [PROP_MENU =>'MENU'
Protected Attributes inherited from IPSRpcModule
$showLogin =[true,true]
$api =null
Current rpc api object.
$lastError =''
Contains the last error of api call.
Protected Attributes inherited from BaseRpcModule
$timerDef =['ONLINE_INTERVAL'=>[0,'s']
Setup the Timers Override this to configure Timers for Module.
$requireLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showLogin =[false,false]
Setup login paramerters used in ApplyChanges and GetConfigurationForm.
$showRefreshButton =false
If true then show config field in formulars to display a refresh button variable.
$online =null
if not checked then $online=null, true if online false if host not reachable
$state =null
State cache if not checked then $state=null, 0=connected | 1=disconnected | 2=error.
$status = null
Status cache if not checked then $status=null.
$prop_names = []
Contains a List of valid Propertys.
Private Member Functions
getDefaulteGroups ()
getDefaultKeyGroups ()
SendKeyCodeMacro ($macros)
SendKeyCodeEx ($k)
Private Attributes
$ValidKeys =['KEY_0','KEY_1','KEY_2','KEY_3','KEY_4','KEY_5','KEY_6','KEY_7','KEY_8','KEY_9','KEY_POWER','KEY_MUTE','KEY_OK','KEY_MENU','KEY_INFO','KEY_RETURN','KEY_OPTIONS','KEY_SRCUP','KEY_SRCDOWN','KEY_PLAY','KEY_PAUSE','KEY_STOP','KEY_NEXT','KEY_PREV','KEY_SHUFFLE','KEY_REPEAT','KEY_FF','KEY_FR','KEY_VOLUP','KEY_VOLDOWN','KEY_UP','KEY_DOWN','KEY_LEFT','KEY_RIGHT']
$KeyValues =['AAAAAgAAADAAAAAJAQ==','AAAAAgAAADAAAAAAAQ==','AAAAAgAAADAAAAABAQ==','AAAAAgAAADAAAAACAQ==','AAAAAgAAADAAAAADAQ==','AAAAAgAAADAAAAAEAQ==','AAAAAgAAADAAAAAFAQ==','AAAAAgAAADAAAAAGAQ==','AAAAAgAAADAAAAAHAQ==','AAAAAgAAADAAAAAIAQ==','AAAAAgAAADAAAAAVAQ==','AAAAAgAAADAAAAAUAQ==','AAAAAgAAADAAAAAMAQ==','AAAAAgAAADAAAABTAQ==','AAAAAgAAADAAAABLAQ==','AAAAAwAAARAAAAB9AQ==','AAAAAwAAARAAAABzAQ==','AAAAAgAAALAAAABqAQ==','AAAAAgAAALAAAABpAQ==','AAAAAwAAARAAAAAyAQ==','AAAAAwAAARAAAAA5AQ==','AAAAAwAAARAAAAA4AQ==','AAAAAwAAARAAAAAxAQ==','AAAAAwAAARAAAAAwAQ==','AAAAAwAAARAAAAAqAQ==','AAAAAwAAARAAAAAsAQ==','AAAAAwAAARAAAAA0AQ==','AAAAAwAAARAAAAAzAQ==','AAAAAgAAADAAAAASAQ==','AAAAAgAAADAAAAATAQ==','AAAAAgAAALAAAAB4AQ==','AAAAAgAAALAAAAB5AQ==','AAAAAgAAALAAAAB6AQ==','AAAAAgAAALAAAAB7AQ==']
Detailed Description
Definition at line 4 of file module.php.
Member Function Documentation
Create()
SonyAVRRemote::Create ()
See also
IPSModule::Create()
Definition at line 9 of file module.php.
References getDefaulteGroups(), and getDefaultKeyGroups().
Destroy()
SonyAVRRemote::Destroy ()
See also
IPSModule::Destroy()
Definition at line 32 of file module.php.
DoUpdate()
SonyAVRRemote::DoUpdate () protected
See also
IPSRpcModule::DoUpdate()
Definition at line 125 of file module.php.
GetConfigurationForm()
SonyAVRRemote::GetConfigurationForm ()
See also
IPSModule::GetConfigurationForm()
Definition at line 44 of file module.php.
getDefaulteGroups()
SonyAVRRemote::getDefaulteGroups () private
Definition at line 184 of file module.php.
References PROP_CURSOR, PROP_MEDIA, PROP_MENU, PROP_NUMBERS, PROP_SOURCE, PROP_SWITCH, and PROP_USER.
Referenced by Create(), and ResetGroups().
getDefaultKeyGroups()
SonyAVRRemote::getDefaultKeyGroups () private
Definition at line 195 of file module.php.
References PROP_CURSOR, PROP_MEDIA, PROP_MENU, PROP_NUMBERS, PROP_SOURCE, and PROP_SWITCH.
Referenced by Create(), and ResetGroups().
GetDiscoverDeviceOptions()
SonyAVRRemote::GetDiscoverDeviceOptions () protected
See also
IPSRpcModule::GetDiscoverDeviceOptions()
Definition at line 117 of file module.php.
GetModuleName()
SonyAVRRemote::GetModuleName ($name, $host) protected
See also
BaseRpcModule::GetModuleName()
Definition at line 110 of file module.php.
GetPropDef()
SonyAVRRemote::GetPropDef ($Ident) protected
See also
BaseRpcModule::GetPropDef()
Definition at line 166 of file module.php.
References PROP_CURSOR, PROP_MEDIA, PROP_MENU, PROP_NUMBERS, PROP_SOURCE, PROP_SWITCH, and PROP_USER.
RequestAction()
SonyAVRRemote::RequestAction ($Ident, $Value)
See also
IPSModule::RequestAction()
Definition at line 19 of file module.php.
References BaseRpcModule\CheckOnline(), SendKeyCodeEx(), and BaseRpcModule\SetValueByIdent().
ResetGroups()
SonyAVRRemote::ResetGroups (bool $ResetMacros)
Parameters
bool $ResetMacros
Definition at line 62 of file module.php.
References getDefaulteGroups(), getDefaultKeyGroups(), and BaseRpcModule\SetProps().
SendKey()
SonyAVRRemote::SendKey (string $Key)
Parameters
string $Key
Returns
boolean
Definition at line 73 of file module.php.
References BaseRpcModule\CheckOnline(), and SendKeyCodeEx().
SendKeyCodeEx()
SonyAVRRemote::SendKeyCodeEx ($k) private
Definition at line 245 of file module.php.
References IPSRpcModule\CallApi().
Referenced by RequestAction(), SendKey(), and SendKeyCodeMacro().
SendKeyCodeMacro()
SonyAVRRemote::SendKeyCodeMacro ($macros) private
Definition at line 232 of file module.php.
References SendKeyCodeEx().
Referenced by SendMacro().
SendMacro()
SonyAVRRemote::SendMacro (string $Name)
Parameters
string $Name
Returns
boolean
Definition at line 82 of file module.php.
References BaseRpcModule\CheckOnline(), and SendKeyCodeMacro().
UpdateProps()
SonyAVRRemote::UpdateProps ($doApply = true) protected
See also
BaseRpcModule::UpdateProps()
Definition at line 130 of file module.php.
References BaseRpcModule\SetProps().
Member Data Documentation
$KeyValues
SonyAVRRemote::$KeyValues =['AAAAAgAAADAAAAAJAQ==','AAAAAgAAADAAAAAAAQ==','AAAAAgAAADAAAAABAQ==','AAAAAgAAADAAAAACAQ==','AAAAAgAAADAAAAADAQ==','AAAAAgAAADAAAAAEAQ==','AAAAAgAAADAAAAAFAQ==','AAAAAgAAADAAAAAGAQ==','AAAAAgAAADAAAAAHAQ==','AAAAAgAAADAAAAAIAQ==','AAAAAgAAADAAAAAVAQ==','AAAAAgAAADAAAAAUAQ==','AAAAAgAAADAAAAAMAQ==','AAAAAgAAADAAAABTAQ==','AAAAAgAAADAAAABLAQ==','AAAAAwAAARAAAAB9AQ==','AAAAAwAAARAAAABzAQ==','AAAAAgAAALAAAABqAQ==','AAAAAgAAALAAAABpAQ==','AAAAAwAAARAAAAAyAQ==','AAAAAwAAARAAAAA5AQ==','AAAAAwAAARAAAAA4AQ==','AAAAAwAAARAAAAAxAQ==','AAAAAwAAARAAAAAwAQ==','AAAAAwAAARAAAAAqAQ==','AAAAAwAAARAAAAAsAQ==','AAAAAwAAARAAAAA0AQ==','AAAAAwAAARAAAAAzAQ==','AAAAAgAAADAAAAASAQ==','AAAAAgAAADAAAAATAQ==','AAAAAgAAALAAAAB4AQ==','AAAAAgAAALAAAAB5AQ==','AAAAAgAAALAAAAB6AQ==','AAAAAgAAALAAAAB7AQ=='] private
Definition at line 222 of file module.php.
$prop_names
array SonyAVRRemote::$prop_names = [PROP_MENU =>'MENU' protected
See also
IPSRpcModule::$prop_names
Definition at line 183 of file module.php.
$showLogin
array SonyAVRRemote::$showLogin =[false,false] protected
See also
BaseRpcModule::$showLogin
Definition at line 104 of file module.php.
$ValidKeys
SonyAVRRemote::$ValidKeys =['KEY_0','KEY_1','KEY_2','KEY_3','KEY_4','KEY_5','KEY_6','KEY_7','KEY_8','KEY_9','KEY_POWER','KEY_MUTE','KEY_OK','KEY_MENU','KEY_INFO','KEY_RETURN','KEY_OPTIONS','KEY_SRCUP','KEY_SRCDOWN','KEY_PLAY','KEY_PAUSE','KEY_STOP','KEY_NEXT','KEY_PREV','KEY_SHUFFLE','KEY_REPEAT','KEY_FF','KEY_FR','KEY_VOLUP','KEY_VOLDOWN','KEY_UP','KEY_DOWN','KEY_LEFT','KEY_RIGHT'] private
Definition at line 221 of file module.php.
PROP_CURSOR
SonyAVRRemote::PROP_CURSOR =>'CURSOR',PROP_NUMBERS=>'NUMBERS',PROP_MEDIA=>'MEDIA',PROP_SOURCE=>'SOURCE',PROP_SWITCH=>'SWITCH', PROP_USER=>'USER']
Definition at line 183 of file module.php.
Referenced by getDefaulteGroups(), getDefaultKeyGroups(), and GetPropDef().
The documentation for this class was generated from the following file:
C:/IP-Symcon/modules/RpcAddOnes/SonyAVRRemote/module.php